In [2]:
#1. Import the NUMPY package under the name np.

import numpy as np

#2. Print the NUMPY version and the configuration.

print(np.__version__)

1.16.2


In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
#4. Print a.

a = np.random.random((2,3,5))
print(a)

[[[0.80182676 0.97966704 0.16963707 0.42973052 0.43187892]
  [0.17340818 0.78641382 0.57219962 0.75606866 0.52960481]
  [0.38045729 0.25004382 0.13841798 0.42262318 0.16166399]]

 [[0.15296981 0.630575   0.20477042 0.6110051  0.75528437]
  [0.1547141  0.67557559 0.68605303 0.10130499 0.81902895]
  [0.38097508 0.756542   0.72908909 0.64335117 0.14718001]]]


In [40]:
a1 = np.random.randint(100,size = (2,3,5))
print(a1)

[[[80 98 75 36 74]
  [70 71  0 54 97]
  [78 83 88 28 27]]

 [[15 73 91 76 47]
  [73 15 84 76 47]
  [35 68 26 11 75]]]


In [8]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
#6. Print b.
b = np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [9]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size == b.size)

True


In [11]:
#8. Are you able to add a and b? Why or why not?
print(np.add(a,b))
# les dimensions de a et b ne sont pas équivalentes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [23]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b, (1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [25]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=np.add(a,c)

In [27]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)
print("d = chaque élément de a + chaque élément de c, donc chaque élément de d = chaque élément de a + 1")

[[[0.80182676 0.97966704 0.16963707 0.42973052 0.43187892]
  [0.17340818 0.78641382 0.57219962 0.75606866 0.52960481]
  [0.38045729 0.25004382 0.13841798 0.42262318 0.16166399]]

 [[0.15296981 0.630575   0.20477042 0.6110051  0.75528437]
  [0.1547141  0.67557559 0.68605303 0.10130499 0.81902895]
  [0.38097508 0.756542   0.72908909 0.64335117 0.14718001]]]
[[[1.80182676 1.97966704 1.16963707 1.42973052 1.43187892]
  [1.17340818 1.78641382 1.57219962 1.75606866 1.52960481]
  [1.38045729 1.25004382 1.13841798 1.42262318 1.16166399]]

 [[1.15296981 1.630575   1.20477042 1.6110051  1.75528437]
  [1.1547141  1.67557559 1.68605303 1.10130499 1.81902895]
  [1.38097508 1.756542   1.72908909 1.64335117 1.14718001]]]
d = chaque élément de a + chaque élément de c, donc chaque élément de d = chaque élément de a + 1


In [28]:
#12. Multiply a and c. Assign the result to e.
e = a * c
print (e)

[[[0.80182676 0.97966704 0.16963707 0.42973052 0.43187892]
  [0.17340818 0.78641382 0.57219962 0.75606866 0.52960481]
  [0.38045729 0.25004382 0.13841798 0.42262318 0.16166399]]

 [[0.15296981 0.630575   0.20477042 0.6110051  0.75528437]
  [0.1547141  0.67557559 0.68605303 0.10130499 0.81902895]
  [0.38097508 0.756542   0.72908909 0.64335117 0.14718001]]]


In [30]:
#13. Does e equal to a? Why or why not?
print(a == e)
print("a = e puisque tout a été multiplié par 1")

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
a = e puisque tout a été multiplié par 1


In [33]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("max de d = ",d_max)
print("min de d = ",d_min)
print("moyenne de d = ",d_mean)

max de d =  1.9796670427195788
min de d =  1.1013049935196397
moyenne de d =  1.4810686793455383


In [35]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))

In [43]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
f[(d < d_mean) & (d > d_min)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_min)] = 0
f[(d == d_max)] = 100
print(f)

[[[ 75. 100.  25.  25.  25.]
  [ 25.  75.  75.  75.  75.]
  [ 25.  25.  25.  25.  25.]]

 [[ 25.  75.  25.  75.  75.]
  [ 25.  75.  75.   0.  75.]
  [ 25.  75.  75.  75.  25.]]]


In [44]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

print(d)
print(f)

[[[1.80182676 1.97966704 1.16963707 1.42973052 1.43187892]
  [1.17340818 1.78641382 1.57219962 1.75606866 1.52960481]
  [1.38045729 1.25004382 1.13841798 1.42262318 1.16166399]]

 [[1.15296981 1.630575   1.20477042 1.6110051  1.75528437]
  [1.1547141  1.67557559 1.68605303 1.10130499 1.81902895]
  [1.38097508 1.756542   1.72908909 1.64335117 1.14718001]]]
[[[ 75. 100.  25.  25.  25.]
  [ 25.  75.  75.  75.  75.]
  [ 25.  25.  25.  25.  25.]]

 [[ 25.  75.  25.  75.  75.]
  [ 25.  75.  75.   0.  75.]
  [ 25.  75.  75.  75.  25.]]]


In [53]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

f[(d < d_mean) & (d > d_min)] = 2
f[(d > d_mean) & (d < d_max)] = 4
f[(d == d_mean)] = 3
f[(d == d_min)] = 1
f[(d == d_max)] = 5

g = np.empty((2,3,5))
for f[i][j][k] in f:
    if f[i][j][k] == 1:
        g[i][j][k].replace ("A")
print(g)

NameError: name 'i' is not defined